image: node:24

definitions:
  caches:
    npmglobal: /usr/local/lib/node_modules

pipelines:
  branches:
    main:
      - step:
          name: Build and deploy to Launch
          deployment: production
          caches: [node, npmglobal]
          script:
            - bash ./deploy.sh
